baseURL = "https://chlzhong.org/"
title = "Chlzhong"
author = "Steve Francia"
copyright = "© 2024-2025, liam.so"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
[pagination]
  pagerSize = 3

# ------------------------------
theme = "hugo-paper"

[params]
  color = 'linen'
  github = 'Liam-Zhong'
  rss = true 
  monoDarkIcon = true
  favicon = "favicon.ico" 

avatar = 'https://pic-private.zhihu.com/v2-1c006a7896b6ece145052d56f0e1e29c~resize:1440:q75.png?source=1f5c5e47&expiration=1760783972&auth_key=1760783972-0-0-0bdc35ce27dc3e5273de1cf592256883&protocol=v2&sampling=False&animatedImagePlayCount=1&overTime=60&incremental=False&sceneCode=article_draft_web&animatedImageAutoPlay=False&retryCount=3&precoder=False&draft_token=704569937'
  name = 'Liam'
  bio = '骋我径寸翰，流藻垂华芬'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true

ignoreFiles = [
  "desktop\\.ini",
  "Thumbs\\.db",
  "\\.DS_Store"
]